spring.application.name=esiusuarios
server.port=8081
logging.file.name=esiusuarios.log

# ============================================================
# BASE DE DATOS - SQL Server
# ============================================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=esiusuarios;encrypt=true;trustServerCertificate=true
spring.datasource.username=esiusuarios_app_user
spring.datasource.password=Diseno2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# ============================================================
# EMAIL - Brevo (SMTP)
# ============================================================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
# El username de Brevo SMTP es el email de la cuenta
spring.mail.username=edugallego23@gmail.com
# La password de Brevo SMTP es la API Key generada
spring.mail.password=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Dirección "De:" que verá el usuario que reciba el correo
app.mail.from=edugallego23@gmail.com

# ============================================================
# SEGURIDAD
# ============================================================
spring.security.user.name=disabled
spring.security.user.password=disabled
# URL base para los enlaces generados en los correos.
app.base-url=http://192.168.1.44:8081
